name: Run Script Daily

on:
  schedule:
    - cron: "0 12 * * *"  # Elke dag om 12:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script
        run: bash weerbulletin.sh
